name: 'Aqua Security Tracee Stop and Check'
description: 'Stop & Checks Tracee results'
author: 'Aqua Security'
inputs:
  workdir:
    description: "Working directory for Tracee"
    required: false
    default: "/tmp/tracee"
  fail-on-diff:
    description: "Fails the check if profile differences are found"
    required: false
    default: 'false'
  create-pr:
    description: "Creates a PR to the default branch with profile differences if found"
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      echo "Stopping Tracee..."
      # sends SIGTERM to the tracee process to stop the container. 
      # this is a temporary solution because tracee is not handling signals properly,
      # so we can use docker kill or docker stop. 
      sudo killall tracee-ebpf
      docker wait tracee-profiler

      ${{ github.action_path }}/stop.sh ${{ inputs.workdir }} ${{ github.token }} ${{ inputs.fail-on-diff }} ${{ inputs.create-pr }}
