name: 'Aqua Tracee'
description: 'Protect your GitHub Actions pipelines with eBPF profiling'
author: 'Aqua Security'
runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      RUNNER_ID=$(id -u runner)
      docker pull aquasec/tracee:latest
      docker run -d --name tracee-profiler --rm --privileged \
      -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host \
      -v /proc:/proc \
      -v /boot:/boot \
      -v /lib/modules/:/lib/modules/:ro \
      -v /etc/os-release:/etc/os-release-host:ro \
      -v /tmp/tracee/:/tmp/tracee \
      -v /usr/src:/usr/src:ro aquasec/tracee:latest \
      trace --trace event=sched_process_exec --trace uid=$RUNNER_ID  \
      --capture exec --output option:exec-hash --output option:exec-env \
      --output out-file:/tmp/tracee/out/trace_$GITHUB_RUN_ID.jsonl --output format:json
      echo -n "Waiting for Tracee to start..."
      until [ -f /tmp/tracee/out/tracee.pid ]
      do
          echo -n "."
          sleep 1
      done
      echo "" #newline
