name: 'Aqua Tracee'
description: 'Protect your GitHub Actions pipelines with eBPF profiling'
author: 'Aqua Security'
inputs:
  fail-on-diff:
    description: "Fails the action if profile deviation found"
    required: false
    default: 'false'
  create-pr:
    description: "Creates a PR to the default branch with profile differences if found"
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      echo "Stopping Tracee..."
      # sends SIGTERM to the tracee process to stop the container. 
      # this is a temporary solution because tracee is not handling signals properly,
      # so we can use docker kill or docker stop. 
      sudo killall tracee-ebpf
      docker wait tracee-profiler
  - shell: bash
    working-directory: ${{github.action_path}}/profile
    run: |
      echo "Generating profile..."
      mkdir /tmp/tracee-action
      profile_config="${{github.workspace}}/.tracee/profile-config.json"
      if [[ ! -f "$profile_config" ]]; then
        profile_config="./profile-config.json"
      fi
      ./profile-gen /tmp/tracee/out/trace_$GITHUB_RUN_ID.jsonl "$profile_config" > /tmp/tracee-action/profile.json
  - shell: bash
    run: |
      echo "Checking profile..."
      ${{github.action_path}}/check.sh /tmp/tracee-action/profile.json ./.tracee/tracee.profile ${{ github.token }} ${{ inputs.fail-on-diff }} ${{ inputs.create-pr }}
