name: 'Aqua Tracee'
description: 'Protect your GitHub Actions pipelines with eBPF profiling'
author: 'Aqua Security'
runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      RUNNER_ID=$(id -u runner)
      docker pull aquasec/tracee:0.10.0
      docker run -d --name tracee --rm \
      --privileged --pid=host --cgroupns=host \
      -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host \
      -v ${{github.action_path}}/signatures/runtime_dropped_executable.rego:/tracee/rules/runtime_dropped_executable.rego \
      -v /proc:/proc \
      -v /boot:/boot \
      -v /lib/modules/:/lib/modules/:ro \
      -v /etc/os-release:/etc/os-release-host:ro \
      -v /tmp/tracee/:/tmp/tracee \
      -v /usr/src:/usr/src:ro \
      --entrypoint=/tracee/tracee \
      aquasec/tracee:0.10.0 \
      --trace uid=$RUNNER_ID  \
      --trace event=stdio_over_socket,aslr_inspection,proc_mem_code_injection,docker_abuse,scheduled_task_mod,ld_preload,cgroup_notify_on_release,default_loader_mod,sudoers_modification,sched_debug_recon,system_request_key_mod,cgroup_release_agent,rcd_modification,core_pattern_modification,proc_kcore_read,proc_mem_access,hidden_file_created,anti_debugging,ptrace_code_injection,process_vm_write_inject,disk_mount,dynamic_code_loading,fileless_execution,illegitimate_shell,kernel_module_loading,proc_fops_hooking,syscall_hooking,runtime_dropped_executable \
      --trace event=sched_process_exec,net_packet_dns \
      --output option:exec-hash --output option:exec-env \
      --output out-file:/tmp/tracee/out/trace_$GITHUB_RUN_ID.jsonl --output format:json
      echo -n "Waiting for Tracee to start..."
      until [ -f /tmp/tracee/out/tracee.pid ]
      do
          echo -n "."
          sleep 1
      done
      echo "" #newline
