apiVersion: aquasecurity.github.io/v1beta1
kind: TraceePolicy
metadata:
  name: signatures
  annotations:
    description: trace signature events
spec:
  scope:
    - global
  rules:
    - event: stdio_over_socket
    - event: aslr_inspection
    - event: proc_mem_code_injection
    - event: docker_abuse
    - event: scheduled_task_mod
    - event: ld_preload
    - event: cgroup_notify_on_release
    - event: default_loader_mod
    - event: sudoers_modification
    - event: sched_debug_recon
    - event: system_request_key_mod
    - event: cgroup_release_agent
    - event: rcd_modification
    - event: core_pattern_modification
    - event: proc_kcore_read
    - event: proc_mem_access
    - event: hidden_file_created
    - event: anti_debugging
    - event: ptrace_code_injection
    - event: process_vm_write_inject
    - event: disk_mount
    - event: fileless_execution
    - event: illegitimate_shell
    - event: kernel_module_loading
    - event: proc_fops_hooking
    - event: syscall_hooking
    - event: dropped_executable
    - event: miner_domain
